steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
  - "-c"
  - |
      curl -X POST -H 'Content-Type: application/json'  -d "{\"repo_name\":\"$_REPO_NAME\}" https://api.sidesp.in/webhooks/cloudbuild
      #curl -X POST -H 'Content-Type: application/json'  -d "{\"repo_name\":\"$_REPO_NAME\", \"turnOff\":true}" https://api.sidesp.in/webhooks/cloudbuild
    #  curl -X POST -H 'Content-Type: application/json'  -d '{"repo_name": ${_IMAGE_NAME}}' https://api.sidesp.in/webhooks/cloudbuild




