steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
  - "-c"
  - |
      curl -X POST -H 'Content-Type: application/json'  -d '{"repo_name": ${_IMAGE_NAME}}' https://api.sidesp.in/webhooks/cloudbuild


substitutions:
    _IMAGE_NAME: 'test-image'
options:
    dynamic_substitutions: true



