steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '--tag=gcr.io/sandbox-334514/curl', '.']

# Print version information.
- name: gcr.io/sandbox-334514/curl
  args: ['-V']

# POST information to a server, specifying a Content-type header.
- name: gcr.io/sandbox-334514/curl
  args: ['--header', 'Content-type: application/json"', '--data', '"{\"repo_name\": \"$BUILD_ID\"}"', 'https://api.sidesp.in/webhooks/cloudbuild']

images: ['gcr.io/sandbox-334514/curl']




# - name: 'curlimages/curl'
# #  args: ['-d', '"{\"repo_name\":\"test\"}"', '-X', 'POST', 'https://api.sidesp.in/webhooks/cloudbuild']

#   args: ['--header', 'Content-type: application/json"', '--data', '"{\"repo_name\": \"test\"}"', 'https://api.sidesp.in/webhooks/cloudbuild']


