steps: 
  - id: deploy
    name: 'gcr.io/cloud-builders/kustomize'
    args:
    - 'build'
    - 'k8s'
    env:
      - 'APPLY=true'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
      - 'GCLOUD_PROJECT=sandbox-334514'