steps:


# POST information to a server, specifying a Content-type header.
# - name: gcr.io/cloud-builders/curl
#   args: ['--header', 'Content-type: application/json"', '--data', '"{\"repo_name\": \"repo_namerepo_name\"}"', 'https://api.sidesp.in/webhooks/cloudbuild']


- name: 'curlimages/curl'
  args: ['-d', '"{\"repo_name\":\"test\"}"', '-X', 'POST', 'http://www.example.com']

# - name: gcr.io/cloud-builders/gcloud
#   entrypoint: "bash"
#   args:
#   - "-c"
#   - |
#       RESPONSE=$(curl -X POST -F 'repo_name=linuxize' https://api.sidesp.in/webhooks/cloudbuild | grep HTTP | cut -d' ' -f2)
#       if [ "200" != "$$RESPONSE" ]; then exit 1; fi

