steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
  - "-c"
  - |
      curl -X POST -H 'Content-Type: application/json'  -d '{"repo_name": $BUILD }' https://api.sidesp.in/webhooks/cloudbuild
  env:
  - 'BUILD=${_REPO_NAME}'




