steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
  - "-c"
  - |
      curl -X POST -H 'Content-Type: application/json'  -d "{\"repo_name\":\"$NAME\", \"turnOff\":true}" https://api.sidesp.in/webhooks/cloudbuild
    #  curl -X POST -H 'Content-Type: application/json'  -d '{"repo_name": ${_IMAGE_NAME}}' https://api.sidesp.in/webhooks/cloudbuild

substitutions:
    _NAME: 'test-image'
options:
    dynamic_substitutions: true



