steps: 
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
  - "-c"
  - |
      RESPONSE=$(curl -i google.com | grep HTTP | cut -d' ' -f2)
      echo $$RESPONSE
      if [ "200" != "$$RESPONSE" ]; then exit 1; fi