steps:


# POST information to a server, specifying a Content-type header.
- name: gcr.io/cloud-builders/curl
  args: ['--header', 'Content-type: application/json"', '--data', '"{\"repo_name\": \"test\"}"', 'https://api.sidesp.in/webhooks/cloudbuild']


# - name: gcr.io/cloud-builders/gcloud
#   entrypoint: "bash"
#   args:
#   - "-c"
#   - |
#       RESPONSE=$(curl -X POST -F 'repo_name=linuxize' https://api.sidesp.in/webhooks/cloudbuild | grep HTTP | cut -d' ' -f2)
#       if [ "200" != "$$RESPONSE" ]; then exit 1; fi

